
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


contract Wallet {

    constructor() public {
        // check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    modifier checkOwnerAndAccept {
        require(msg.pubkey() == tvm.pubkey(), 100);
		tvm.accept();
		_;
	}

    function sendTransactionWithComission(address dest, uint128 value, bool bounce) public pure checkOwnerAndAccept {
        
        dest.transfer(value, bounce, 1);
    }

    function sendTransactionWithoutComission(address dest, uint128 value, bool bounce) public pure checkOwnerAndAccept {
        
        dest.transfer(value, bounce, 0);
    }

    function sendTransactionAllAndDestroy(address dest, bool bounce) public pure checkOwnerAndAccept {
        
        dest.transfer(0, bounce, 160);
    }
}