
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameUnit.Sol";

contract Archer is GameUnit {

    constructor(BaseStation _base) GameUnit(_base) public{
        damage = 5;
        defence = 0;
    }

}
