
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

abstract contract AHasConstructorWithPubKey {
   constructor(uint256 pubkey) public {}
}