
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "itemStructs.sol";

interface IItemList {
    function addItem(string name, uint64 count) external;
    function buyItem(uint32 id, uint256 price) external;
    function deleteItem(uint32 id) external;
    function getStat() external returns (ItemsSummary itemsSummary);
    function getItems() external returns (Item[] items);
}