
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "AShoppingListInitDebot.sol";

contract shoppingListFillerDebot is AShoppingListInitDebot {

        /// @notice Returns Metadata about DeBot.
    function getDebotInfo() public functionID(0xDEB) override view returns(
        string name, string version, string publisher, string key, string author,
        address support, string hello, string language, string dabi, bytes icon
    ) {
        name = "Shopping List DeBot";
        version = "0.2.0";
        publisher = "PlaNex";
        key = "Shopping list manager";
        author = "PlaNex";
        support = address.makeAddrStd(0, 0x66e01d6df5a8d7677d9ab2daf7f258f1e2a7fe73da5320300395f99e01dc3b5f);
        hello = "Hi, i'm a Shopping list DeBot.";
        language = "en";
        dabi = m_debotAbi.get();
        icon = m_icon;
    }

    function _menu() override internal {
        string sep = '----------------------------------------';
        Menu.select(
            format(
                "You have {}/{}/{} (not bought/bought/total) items, total price: {}",
                    m_itemsSummary.notBoughtCount,
                    m_itemsSummary.boughtCount,
                    m_itemsSummary.boughtCount + m_itemsSummary.notBoughtCount,
                    m_itemsSummary.totalPrice
            ),
            sep,
            [
                MenuItem("Add new Item","",tvm.functionId(addItem)),
                MenuItem("Show Item list","",tvm.functionId(showItems)),
                MenuItem("Delete Item","",tvm.functionId(deleteItem))
            ]
        );
    }

}
